/*
 * vfd_config.h
 *
 *  Created on: Nov 10, 2025
 *      Author: bahromiddin
 */

#ifndef INC_VFD_CONFIG_H_
#define INC_VFD_CONFIG_H_

#define VFD_MONITORING_ADDRESS ((uint16_t)0x9000) // read 5 address frome 0x9000
#define VFD_SET_FREQ_ADDRESS ((uint16_t)0xA001)   // write 1 address to 0xA001 (00.00~100.00 indicates 00.00%~100.00%)
#define VFD_STATUS_ADDRESS ((uint16_t)0xB000)     // read 1 address frome 0xB000
#define VFD_ISSUE_ADDRESS ((uint16_t)0xB001)      // read 1 address frome 0xB001

#define VFD_MONITORING_DATA_LEN 5
#define VFD_STATUS_DATA_LEN 1
#define VFD_ISSUE_DATA_LEN 1

/* Error Codes */
#define VFD_SUCCESS              0
#define VFD_ERROR_INVALID_PARAM -1
#define VFD_ERROR_MODBUS_FAIL   -2
#define VFD_ERROR_OUT_OF_RANGE  -3


typedef enum {
    VFD_NONE = 0,
    VFD_FORWARD_RUN,
    VFD_REVERSE_RUN,
    VFD_STOP,
    VFD_STATUS_COUNT
} vfd_status;


typedef enum  uint8_t {
  VFD_NO_FAULT = 0,
  VFD_OVER_CURRENT_CONSTANT_SPEED,
  VFD_OVER_CURRENT_ACCELERATION,
  VFD_OVER_CURRENT_DECELERATION,
  VFD_OVER_VOLTAGE_CONSTANT_SPEED,
  VFD_OVER_VOLTAGE_ACCELERATION,
  VFD_OVER_VOLTAGE_DECELERATION,
  VFD_MODULE_FAULT,
  VFD_UNDERVOLTAGE,
  VFD_FREQUENCY_INVERTER_OVERLOAD,
  VFD_MOTOR_OVERLOAD,
  VFD_INPUT_DEFAULT_PHASE,
  VFD_OUTPUT_DEFAULT_PHASE,
  VFD_EXTERNAL_FAULT,
  VFD_ABNORMAL_COMMUNICATION,
  VFD_INVERTER_OVERHEAT,
  VFD_INVERTER_HARDWARE_FAULT,
  VFD_MOTOR_EARTHING_SHORT_CIRCUIT,
  VFD_MOTOR_IDENTIFICATION_ERROR,
  VFD_MOTOR_OFFLOAD,
  VFD_PID_FEEDBACK_LOSS,
  VFD_USER_DEFINED_FAULT_1,
  VFD_USER_DEFINED_FAULT_2,
  VFD_POWER_ON_TIME_REACHED,
  VFD_RUNNING_TIME_REACHED,
  VFD_ENCODER_FAULT,
  VFD_PARAM_RW_ABNORMITY,
  VFD_MOTOR_OVERHEAT,
  VFD_LARGE_SPEED_DEVIATION,
  VFD_MOTOR_OVERSPEED,
  VFD_INITIAL_POSITION_ERROR,
  VFD_CURRENT_TEST_FAULT,
  VFD_CONTACTOR,
  VFD_CURRENT_TEST_ABNORMITY,
  VFD_FAST_CURRENT_LIMIT_TIMEOUT,
  VFD_MOTOR_SWITCH_RUNNING,
  VFD_24V_POWER_FAULT,
  VFD_DRIVING_POWER_FAULT,
  VFD_BUFFER_RESISTANCE_FAULT,
  VFD_ISSUE_COUNT
} vfd_issue;


#endif /* INC_VFD_CONFIG_H_ */
